---

- name: Provision dependencies
  hosts: all
  gather_facts: no
  tasks:
    - name: Update package lists
      raw: apk update

    - name: Install python
      raw: apk add --no-cache python

    - name: Install dependencies
      command: apk add --no-cache make

- name: Provision application
  hosts: all

  tasks:
    #- name: Change directory permission
      #file:
        #path: /go/src/github.com/Hendra-Huang/go-standard-layout/
        #state: directory
        #mode: 0777
        #owner: root
        #group: root
        #recurse: yes
    #- name: Copy application
      #synchronize:
        #src: ./
        #dest: /go/src/github.com/Hendra-Huang/go-standard-layout/
    #- name: Find files to copy
      #delegate_to: localhost
      #connection: local
      #run_once: true
      #find:
        #paths: "./"
        #file_type: "file"
        #recurse: yes
      #register: webservice

    #- name: Copy application
      #copy:
        #src: "{{ item.path }}"
        #dest: /go/src/github.com/Hendra-Huang/go-standard-layout/
        #mode: 0755
        #owner: root
        #group: root

    - name: Build binary
      shell: make build
      args:
        chdir: /go/src/github.com/Hendra-Huang/go-standard-layout/

    - name: Copy binary
      command: cp -r bin/ /usr/local/bin/
      args:
        chdir: /go/src/github.com/Hendra-Huang/go-standard-layout/

- name: Container cleanup
  hosts: all
  gather_facts: no
  tasks:
    - name: Remove package lists
      command: rm -rf /var/cache/apk/*

    - name: Remove dependencies
      command: apk del make

    - name: Remove go
      command: rm -rf /usr/local/go /go/src /go/bin /go/pkg

    - name: Remove python
      raw: apk del python
